(ns status-im.react-native.resources
  (:require [status-im.ui.components.colors :as colors]))

(def ui
  {:empty-chats-header (js/require (str js/RESOURCES_DIR "/images/ui/empty-chats-header.png"))
   :welcome            (js/require (str js/RESOURCES_DIR "/images/ui/welcome.jpg"))
   :welcome-dark       (js/require (str js/RESOURCES_DIR "/images/ui/welcome-dark.jpg"))
   :chat               (js/require (str js/RESOURCES_DIR "/images/ui/chat.jpg"))
   :wallet             (js/require (str js/RESOURCES_DIR "/images/ui/wallet.jpg"))
   :browser            (js/require (str js/RESOURCES_DIR "/images/ui/browser.jpg"))
   :chat-dark          (js/require (str js/RESOURCES_DIR "/images/ui/chat-dark.jpg"))
   :wallet-dark        (js/require (str js/RESOURCES_DIR "/images/ui/wallet-dark.jpg"))
   :browser-dark       (js/require (str js/RESOURCES_DIR "/images/ui/browser-dark.jpg"))
   :keys               (js/require (str js/RESOURCES_DIR "/images/ui/keys.jpg"))
   :keys-dark          (js/require (str js/RESOURCES_DIR "/images/ui/keys-dark.jpg"))
   :lock               (js/require (str js/RESOURCES_DIR "/images/ui/lock.png"))
   :tribute-to-talk    (js/require (str js/RESOURCES_DIR "/images/ui/tribute-to-talk.png"))
   :hardwallet-card    (js/require (str js/RESOURCES_DIR "/images/ui/hardwallet-card.png"))
   :keycard-lock       (js/require (str js/RESOURCES_DIR "/images/ui/keycard-lock.png"))
   :keycard            (js/require (str js/RESOURCES_DIR "/images/ui/keycard.png"))
   :keycard-logo       (js/require (str js/RESOURCES_DIR "/images/ui/keycard-logo.png"))
   :keycard-logo-blue  (js/require (str js/RESOURCES_DIR "/images/ui/keycard-logo-blue.png"))
   :keycard-logo-gray  (js/require (str js/RESOURCES_DIR "/images/ui/keycard-logo-gray.png"))
   :keycard-key        (js/require (str js/RESOURCES_DIR "/images/ui/keycard-key.png"))
   :keycard-empty      (js/require (str js/RESOURCES_DIR "/images/ui/keycard-empty.png"))
   :keycard-phone      (js/require (str js/RESOURCES_DIR "/images/ui/keycard-phone.png"))
   :keycard-connection (js/require (str js/RESOURCES_DIR "/images/ui/keycard-connection.png"))
   :keycard-wrong      (js/require (str js/RESOURCES_DIR "/images/ui/keycard-wrong.png"))
   :not-keycard        (js/require (str js/RESOURCES_DIR "/images/ui/not-keycard.png"))
   :status-logo        (js/require (str js/RESOURCES_DIR "/images/ui/status-logo.png"))
   :warning-sign       (js/require (str js/RESOURCES_DIR "/images/ui/warning-sign.png"))
   :phone-nfc-on       (js/require (str js/RESOURCES_DIR "/images/ui/phone-nfc-on.png"))
   :phone-nfc-off      (js/require (str js/RESOURCES_DIR "/images/ui/phone-nfc-off.png"))
   :dapp-store         (js/require (str js/RESOURCES_DIR "/images/ui/dapp-store.png"))
   :ens-header         (js/require (str js/RESOURCES_DIR "/images/ui/ens-header.png"))
   :ens-header-dark    (js/require (str js/RESOURCES_DIR "/images/ui/ens-header-dark.png"))
   :new-chat-header    (js/require (str js/RESOURCES_DIR "/images/ui/new-chat-header.png"))
   :onboarding-phone   (js/require (str js/RESOURCES_DIR "/images/ui/onboarding-phone.png"))
   :theme-dark         (js/require (str js/RESOURCES_DIR "/images/ui/theme-dark.png"))
   :theme-light        (js/require (str js/RESOURCES_DIR "/images/ui/theme-light.png"))
   :theme-system       (js/require (str js/RESOURCES_DIR "/images/ui/theme-system.png"))})

(defn get-theme-image [k]
  (get ui (when (colors/dark?) (keyword (str (name k) "-dark"))) (get ui k)))

(def loaded-images (atom {}))

(defn get-image [k]
  (if (contains? @loaded-images k)
    (get @loaded-images k)
    (get (swap! loaded-images assoc k
                (get ui k)) k)))
